importJsonSchema("examples/address/schema.json", conf("Address"))
importJsonSchema("examples/blog/schema.json", conf("Blog"))
importJsonSchema("examples/location/schema.json", conf("Location"))
importJsonSchema("examples/health/schema.json", conf("Health"))
importJsonSchema("examples/movie/schema.json", conf("Movie"))
importJsonSchema("examples/user_profile/schema.json", conf("UserProfile"))
importJsonSchema("examples/basic/schema.json", conf("Basic"))
importJsonSchema("examples/array_of_things/schema.json", conf("ArrayOfThings"))
importJsonSchema("examples/enumerated_values/schema.json", conf("EnumeratedValues"))
importJsonSchema("examples/complex_object/schema.json", conf("ComplexObject"))
importJsonSchema("examples/union/schema.json", conf("Union"))
importJsonSchema("examples/file_system/schema.json", conf("FileSystem"))
importJsonSchema("examples/ecommerce/schema.json", conf("Ecommerce"))
importJsonSchema("examples/ldtk/schema.json", conf("Ldtk"))
importJsonSchema("examples/aseprite/schema.json", conf("Aseprite"))
importJsonSchema("examples/consts/schema.json", conf("Consts"))
importJsonSchema("examples/empty_object/schema.json", conf("EmptyObject"))
importJsonSchema(
  "examples/optional_empty_object/schema.json", conf("OptionalEmptyObject")
)
importJsonSchema("examples/untyped_array/schema.json", conf("UntypedArray"))
importJsonSchema(
  "examples/unconstrained_object/schema.json", conf("UnconstrainedObject")
)
importJsonSchema("examples/bool_schema/schema.json", conf("BoolSchema"))
importJsonSchema("examples/array_root/schema.json", conf("ArrayRoot"))
importJsonSchema("examples/string_root/schema.json", conf("StringRoot"))
importJsonSchema("examples/const_root/schema.json", conf("ConstRoot"))
importJsonSchema("examples/union_root/schema.json", conf("UnionRoot"))
importJsonSchema("examples/merged_scalars/schema.json", conf("MergedScalars"))
importJsonSchema("examples/nullable_merge/schema.json", conf("NullableMerge"))
importJsonSchema("examples/union_discriminator/schema.json", conf("UnionDiscriminator"))
importJsonSchema("examples/narrowed_union/schema.json", conf("NarrowedUnion"))
importJsonSchema("examples/const_typed/schema.json", conf("ConstTyped"))
importJsonSchema("examples/open_object/schema.json", conf("OpenObject"))
importJsonSchema("examples/ref_siblings/schema.json", conf("RefSiblings"))
importJsonSchema("examples/all_of/schema.json", conf("AllOf"))
importJsonSchema("examples/tuples/schema.json", conf("Tuples"))
importJsonSchema("examples/standalone_required/schema.json", conf("StandaloneRequired"))
importJsonSchema("examples/recursive_tree/schema.json", conf("RecursiveTree"))
importJsonSchema("examples/linked_list/schema.json", conf("LinkedList"))
importJsonSchema("examples/mutual_refs/schema.json", conf("MutualRefs"))
importJsonSchema("examples/recursive_union/schema.json", conf("RecursiveUnion"))
importJsonSchema("examples/enum_value_collision/schema.json", conf("EnumValueCollision"))
