importJsonSchema("examples/address/schema.json", conf("Address"))
importJsonSchema("examples/blog/schema.json", conf("Blog"))
importJsonSchema("examples/location/schema.json", conf("Location"))
importJsonSchema("examples/health/schema.json", conf("Health"))
importJsonSchema("examples/movie/schema.json", conf("Movie"))
importJsonSchema("examples/user_profile/schema.json", conf("UserProfile"))
importJsonSchema("examples/basic/schema.json", conf("Basic"))
importJsonSchema("examples/array_of_things/schema.json", conf("ArrayOfThings"))
importJsonSchema("examples/enumerated_values/schema.json", conf("EnumeratedValues"))
importJsonSchema("examples/complex_object/schema.json", conf("ComplexObject"))
importJsonSchema("examples/union/schema.json", conf("Union"))
importJsonSchema("examples/file_system/schema.json", conf("FileSystem"))
importJsonSchema("examples/ecommerce/schema.json", conf("Ecommerce"))
importJsonSchema("examples/ldtk/schema.json", conf("Ldtk"))
importJsonSchema("examples/aseprite/schema.json", conf("Aseprite"))
importJsonSchema("examples/consts/schema.json", conf("Consts"))
importJsonSchema("examples/empty_object/schema.json", conf("EmptyObject"))
importJsonSchema(
  "examples/optional_empty_object/schema.json", conf("OptionalEmptyObject")
)
importJsonSchema("examples/untyped_array/schema.json", conf("UntypedArray"))
importJsonSchema(
  "examples/unconstrained_object/schema.json", conf("UnconstrainedObject")
)
importJsonSchema("examples/bool_schema/schema.json", conf("BoolSchema"))
importJsonSchema("examples/array_root/schema.json", conf("ArrayRoot"))
importJsonSchema("examples/string_root/schema.json", conf("StringRoot"))
importJsonSchema("examples/const_root/schema.json", conf("ConstRoot"))
importJsonSchema("examples/union_root/schema.json", conf("UnionRoot"))
importJsonSchema("examples/merged_scalars/schema.json", conf("MergedScalars"))
importJsonSchema("examples/nullable_merge/schema.json", conf("NullableMerge"))
importJsonSchema("examples/union_discriminator/schema.json", conf("UnionDiscriminator"))
