name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: nimlang/choosenim
    steps:
    - run: choosenim update -y 2.2.0
    - uses: actions/checkout@v3
    - run: git config --global --add safe.directory "$(pwd)"
    - run: nimble test
